### PR TITLE
Utilise useYarn flag to install app template with yarn

### PR DESCRIPTION
**Pull request by culshaw**
This PR will make the `--yarn` install flag use yarn for the entire pipeline of spinning a projectt up for create-snowpack-app

### CODE REVIEW

**Comment by FredKSchott** [comment]
Was npm not working for you here? `--use-yarn` was meant more to let you set which one to use in your project, and less about which is used internally to set up your project.

I'm not opposed to the change as long as it fixes something for you.

**Comment by culshaw** [comment]
It was working for me yes, but when I use the `--use-yarn` flag I was surprised to see it using npm and assumed it was a mistake.

**Comment by FredKSchott** [comment]
I just realized that I don't think this will work with yarn v2, since we expect the package to exist in your local node_modules folder. Were you able to test with yarn 2?

**Comment by culshaw** [comment]
I'll check later today, I am indeed using v1 :)

**Comment by FredKSchott** [comment]
sounds good

**Comment by culshaw** [comment]
i tried with v2, it might be how I'm using it but v2 just doesn't work at _all_.

I'm using yarn link and it does some madness with resolutions, not sure if it's syncing up correctly but complains about not having `semver` installed. Which I'm sure isn't even necessary.

Will close this for a while

**Pull request closed without merging**
