### PR TITLE
Add app-scripts-preact and app-template-preact

### PR DESCRIPTION
**Pull request by sventschui**
Add app-scripts-preact and app-template-preact based on the react scripts/template.

I first tried to adjust the app-scripts-react to also support preact but with a custom babel.config.json I ran into issues (with snowpack 0.3.0) and then found the jest setup to heavily rely on React I decided to "fork" it to app-scripts-preact. I'd be happy to make the app-scripts-react "preact"-compatible when you are okay with:
- Dropping `babel-preset-react-app` as it doesn't support configuring the jsx pragma
- Have a mechanism to detect preact (somehow set an env var, have config option for snowpack's extend similar to babel presets, ...) and then adjust the jest transforms/babel.config.js(on) to use preact if that detection triggers.

image

### CODE REVIEW

**Comment by FredKSchott** [comment]
this is awesome! I'm fine having them as separate, it should give us more flexibility. I'll review today!

/cc @developit since we'd talked about this earlier in the week

**Comment by developit** [comment]
This is great!

**Comment by FredKSchott** [comment]
Looks great! I'm going to do a little cleanup after merging to both the React & Preact templates now that we have two to manage.

Screen Shot 2020-05-08 at 1 32 29 PM

Looks like VSCode (via TypeScript) thinks `h` is unused, but it doesn't complain about React ever being unused with JSX. Not blocking, but any tricks for solving this that we could leverage?

**Comment by FredKSchott** [comment]
Thanks @sventschui!

**Comment by FredKSchott** [comment]
also just as a heads up, I had to remove the Preact logo component before merging, since the code came from another repo and wasn't properly licensed. 

Added bonus: keeping the code itself simple means that we don't take a strong stance on how to write the framework-specific code :)

**Comment by marvinhagemeister** [comment]
@FredKSchott If the `"h" is unused` error is coming from TypeScript you can resolve that by adding `jsxFactory: "h"` to `tsconfig.json`.

**Comment by sventschui** [comment]
> also just as a heads up, I had to remove the Preact logo component before merging, since the code came from another repo and wasn't properly licensed.

Sorry for that one, I copied it from our website and thought it's gonna be okay since I'm on the core team :)

**Comment by sventschui** [comment]
@FredKSchott What's required to bring the template to (a) the website and (b) make it installable via create-snowpack-app (it currently tried to find a package named like that on npm)?

**Comment by FredKSchott** [comment]
@sventschui np! This should already be published under the preact package name, which is how the installer works.

```
npx create-snowpack-app new-dir --template @snowpack/app-template-preact
```

**Comment by sventschui** [comment]
Ah silly me. Forgot the snowpack namespace 🤦‍♂️ Thanks!

**Pull request merged**
